spring:
  datasource:
#    url: jdbc:mysql://47.98.119.221:6612/happyh?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://47.98.119.221:6612/happy?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      test-on-borrow: true
      test-while-idle: true
    dbcp2:
      default-auto-commit:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true
  activemq:
